//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcuaDeliveryV3
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROVEEDOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROVEEDOR()
        {
            this.PRODUCTOS = new HashSet<PRODUCTO>();
        }
    
        public int PRV_ID { get; set; }
        public string PRV_NOMBRE { get; set; }
        public string PRV_RUC { get; set; }
        public string PRV_TELEFONO { get; set; }
        public string PRV_EMAIL { get; set; }
        public string PRV_DESCRIPCION { get; set; }
        public string PRV_CONTRASENA { get; set; }
        public string PRV_DIRECCION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCTO> PRODUCTOS { get; set; }
    }
}
